In [1]:
import numpy as np

#Create a 1D array with 12 elements
arr = np.arange(12)

#Reshape the array into 3 rows and 4 columns
reshaped_arr = arr.reshape(3, 4)

print("Reshaped Array:")
print(reshaped_arr)

print("Summation of each column:")
print(np.sum(reshaped_arr, axis=0))

print("Summation of each row:")
print(np.sum(reshaped_arr, axis=1))

print("Summation of matrix:")
print(np.sum(reshaped_arr))

Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Summation of each column:
[12 15 18 21]
Summation of each row:
[ 6 22 38]
Summation of matrix:
66


In [3]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr1 * arr2

array([ 5, 12, 21, 32])

In [8]:
# given a 2d numpy array, find the index of the maximum element in each column
# hint: use argmax function
arr = ([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
indices = np.argmax(arr, axis=1)

print ("indices of maximum elements in each column:")
print(indices)

indices of maximum elements in each column:
[2 2 2]


In [9]:
# given a 2d numpy array, compute the mean of each row

([1, 2, 3], [4, 5, 6], [7, 8, 9])
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# compute the mean of each row
means = np.mean(arr, axis=1)

print ("mean of each row:")
print(means)

mean of each row:
[2. 5. 8.]


In [11]:
# filter elements from a numpy array that are greater than a given threshold using boolean indexing
arr = np.array([1, 5, 8, 12, 20, 3])
threshold = 10
filtered_arr = arr[arr > threshold]

print ("filtered array:")
print(filtered_arr)

filtered array:
[12 20]


In [ ]:
# find the dot product of two numpy vectors
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

dot_product = np.dot(vec1, vec2)

print ("dot product:")
print(dot_product)

In [ ]:
# calculate the cosine similarity between two numpy vectors
def cosine_similarity(vec1, vec2)
dot_product = np.doc(vec1, vec2)
norm_vec1 = np.linalg.norm(vec1)
norm_vec2 = np.linalg.norm(vec2)
return dot_product / (norm_vec1 * norm_vec2)

similarity = cosine_similarity(vec1, vec2)

print ("cosine similarity:")
print(similarity)

In [18]:
# calculate the euclidean distance between two points in a 2d space using numpy

vec1 = np.array([1, 2])
vec2 = np.array([4, 5])

def euclidean_distance(point1, point2):
  return np.linalg.norm(point1 - point2)

distance = euclidean_distance(vec1, vec2)

print ("euclidean distance:")
print(distance)

euclidean distance:
4.242640687119285
